<link rel="stylesheet" href="assets/css/custom.css">


theme: jekyll-theme-midnight
title: Ceja Florendo – Portfolio
description: Robotics • Mechatronics • Verification & Validation
include: ["assets/css"]

